### ISSUE TITLE
GC overhead limit exceeded or java heap space in AfterStories

### ISSUE THREAD

**Issue by anujbajaj** [serenity-bdd/serenity-jbehave#69]
Dear Team,

We are using Serenity version 1.1.26 & have been facing an issue in AfterStories. 

We are executing 320+ unit test cases & they run fine (around 1 hour) however in AfterStories, when Serenity tries to copy all xml & html reports (there are around 1000+ files) to the output directory, it is taking couple of hours & after that it is resulting in either "GC overhead limit exceeded" or "java heap space" errors which is resulting in missing index.html file.

We tried the same thing with Thucydides & it works fine with it. 

Request you to please look into this & update.

Regards,
Anuj

**Comment by YamStranger** [comment]
Hello @anujbajaj 
Please check it with latest serenity - there was updated reporting mechanism. 

Thanks a lot!!!

**Comment by anujbajaj** [comment]
Hi @YamStranger 

Which one is the latest stable version of Serenity?

We tried with 1.1.28 with JBehave version as 1.9.0 however it is throwing below error.

ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

Please note that we are running web services tests.

Regards,
Anuj

**Comment by YamStranger** [comment]
Hello @anujbajaj 

Please use 1.1.29-rc.2 - here included moving of report files and generating report files using tmp files. Also fixed some "close-stream" issues. 
also jbehave 1.9.0 should be used with 1.1.29-rc.2 serenity core.

about your exception: 
>ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

it can be because of using old selenium or webdriver for firefox (and new webdriver require new firefox as well, please follow webdriver documentation)

This exception will appear if you have some webdriver-initialisation code, so I think that some of your tests are used webdriver... Are you sure that you did not use web driver at all in them? 

Thanks

**Comment by anujbajaj** [comment]
Hello @YamStranger 

Thanks for the update. We will try using Serenity version as mentioned above & will see if there is any issues.

Also our tests are completely web service based & does not require any web driver initialization.

Regards,
Anuj

**Comment by wakaleo** [comment]
Hi Anuj,

If your tests are web service based, you can drop the @Managed driver entirely - it’s only needed for web testing. 


___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 12 April 2016 at 9:03:38 PM, anujbajaj (notifications@github.com) wrote:

Hello @YamStranger

Thanks for the update. We will try using Serenity version as mentioned above & will see if there is any issues.

Also our tests are completely web service based & does not require any web driver initialization.

Regards,
Anuj

**Comment by anujbajaj** [comment]
Hi @wakaleo 

We are not using @Managed annotation anywhere in our project.

As suggested by @YamStranger, I tried using Serenity 1.1.29-rc.2 however it is opening Firefox browser before every JBehave story.

Regards,
Anuj

**Comment by wakaleo** [comment]
In that case it does sound like a bug - we will investigate further..

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 12 April 2016 at 9:39:35 PM, anujbajaj (notifications@github.com) wrote:

Hi @wakaleo

We are not using @Managed annotation anywhere in our project.

As suggested by @YamStranger, I tried using Serenity 1.1.29-rc.2 however it is opening Firefox browser before every JBehave story.

Regards,
Anuj

**Comment by YamStranger** [comment]
@wakaleo Yes for sure - created ticket for it (#70)
@anujbajaj I see that #70 can be critical for you (because length of your tests will increase dramatically), will try to fix it as soon as possible. For now please try to use workaround:

make serenity BDD use HTMLUnit (it should be included in serenity-core)
for example you can add parameter in command line during executing your test:
```
-Dwebdriver.driver=htmlunit
```
or include it in serenity.properties
in such case serenity will not require firefox and will use htmlunit. Yes it will init it, and bug will not disappear - but initialization of html driver will much faster then other browsers.

Thanks

**Comment by YamStranger** [comment]
@anujbajaj did you have chance to run your test with core 1.1.28 with JBehave version as 1.9.0 and htmlunit config.  

Did you face same issue as described:
>We are executing 320+ unit test cases & they run fine (around 1 hour) however in AfterStories, when Serenity tries to copy all xml & html reports (there are around 1000+ files) to the output directory, it is taking couple of hours & after that it is resulting in either "GC overhead limit exceeded" or "java heap space" errors which is resulting in missing index.html file.

thanks

**Comment by YamStranger** [comment]
@anujbajaj 
Issue with webdriver have fixed - will be in next release.

**Comment by anujbajaj** [comment]
Thanks @YamStranger 

Which Serenity & JBehave version we can use now which has the fix?

Regards,
Anuj

**Comment by YamStranger** [comment]
Hello @anujbajaj 
jbehave 1.10.0 and core - v1.1.32-rc.1

**Comment by YamStranger** [comment]
@anujbajaj have you change to check this issue with new updated core and jbehave ? 

Now it should work property, and issue with webdriver is fixed. 

Thanks!

**Comment by YamStranger** [comment]
It seems that this issue is fixed in latest serenity-core, and ticket can be closed. 

Thanks!
