### ISSUE TITLE
Property serenity.use.unique.browser does not work

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-jbehave#72]
It should work based on [manual](http://thucydides.info/docs/serenity-staging/#_running_all_tests_in_a_single_browser_window)

**Comment by YamStranger** [comment]
Issue can be reproduced for:
serenity-junit
serenity-jbehave
serenity-cucumber
tested with firefox browser, used as serenity.use.unique.browser = false

**Comment by YamStranger** [comment]
Checked all deeply with serenity-junit all works as expect (manual is not correct, browser is shared between tests (test methods), but not between test suites (test classes))

**Comment by YamStranger** [comment]
Hello @lukateklic!

Can you provide a little bit more information:
Did you use serenity-junit or serenity-jbehave or serenity-cucumber in your tests (based on  #396 issue)?

**Comment by YamStranger** [comment]
@lukateklic, unfortunately documentation should be updated, ticket: serenity-bdd/serenity-documentation/issues/67 was created with short description. 

For jbehave using of same browser for same story - it is default behaving, so it should work fine for all your tests. 

Unfortunately executing all test suites (scenario, or test class) in one browser is impossible

**Comment by YamStranger** [comment]
@lukateklic
Manual is updated. 

Thanks for this issue!!

**Comment by mathieudruart** [comment]
Hello !

We are currently using Serenity with JBehave (serenity-core 1.1.2 / serenity-jbehave 1.1.0 / JBehave 4.0.5), until now all tests of all stories were executed in the same browser (the browser is not closed/reopened between stories). It was the expected behaviour for us when using runSerenity().inASingleSession(), as documented in the former version of the manual.

We tried to update serenity-core (to 1.1.31) and serenity-jbehave (to 1.9.0) and we discovered that the behaviour changed.

Was it changed on purpose ? Is there a way to reproduce the former behaviour ?

For now we rolled back to the old version.

Thank you !

**Comment by YamStranger** [comment]
Hello @mathieudruart 

All scenario of one story executed in same browser, but new browser is used for each story:

story 1
  scenario 1
  scenario 2

story 2
  scenario 3
  scenario 4

if inASingleSession enabled (but default is is enabled) scenario 3 and 4 will be executed in one browser, but not in same browser as scenario 1 and 2. 

Please take  a look on updated manual

**Comment by mathieudruart** [comment]
@YamStranger we understand that it is the behaviour of the current version, but it was not the behaviour in the past versions (at least until serenity-core 1.1.2).

In the 1.1.2 version of serenity, all scenarios of all stories are executed in the same browser.

In your example, scenarios 1, 2, 3 and 4 are executed in one browser.

I don't know the version that changed this behaviour (somewhere between 1.1.2 and 1.1.31), that's why I asked if it was a change made on purpose ?

**Comment by ManuelAbril** [comment]
Hi everyone,

I am having problems with that topic. I want to use an unique browser although my tests fail. This is my build gradle:
````
compile group: 'junit', name: 'junit', version: '4.12'
compile group: 'net.serenity-bdd', name: 'serenity-core', version: '1.2.2'
compile group: 'net.serenity-bdd', name: 'serenity-jbehave', version: '1.21.0'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.2.2'
````

This is my serenity properties:
````
serenity.use.unique.browser = true
restart.browser.each.scenario = false
thucydides.use.unique.browser = true
serenity.maintain.session = false
````

Finally, my tests are base on Jbehave and I created a customer Runner which extends SerenityStories. It only has additonal configuration for Jbehave, like creating new converters for steps.

What am I doing wrongly?
