### ISSUE TITLE
Combining jbehave metafilters is causing unexpected scenarios/example to be executed

### ISSUE THREAD

**Issue by samuelMangot** [serenity-bdd/serenity-jbehave#77]
Hi, 

By running the latest stable version of serenity-core (1.1.32) and serenity-jbehave (1.9.0) available at the Maven central, jbehave metafiltering got broken in my existing serenity story repositories.

Here's a short description of the way I apply metafiltering in my project: 

> Scenario: I want to filter story execution by Meta 
> Meta:
> @context clientCode1
> Given ...
> When...
> Then...

or By using example tables such as:

> Scenario: I want to filter story examples execution by Meta 
> Meta:
> @context 
> Given ...<clientCode>
> When...
> Then...
> Examples:
> |clientCode|
> |clientCode1|
> |clientCode2|

I'm running serenity test execution using serenity-maven-plugin and setting environment variable as follows:
**-Dmetafilter="+context clientCode1 +featureA -featureB**

In order to be able to keep the existing filtering feature in my repos I had to revert back to serenity-jbehave v 1.6.0

Can you tell if I miss something on if there is a sneaky bug or something ?

**Comment by wakaleo** [comment]
Hi Samuel,

I don’t recall much changing in the Serenity code regarding JBehave features, could it be related to the latest JBehave version?


___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
___________________________________________________


On 3 May 2016 at 1:36:04 PM, Samuel Mangot (notifications@github.com) wrote:

Hi,

By running the latest stable version of serenity-core (1.1.32) and serenity-jbehave (1.9.0) available at the Maven central, jbehave metafiltering got broken in my existing serenity story repositories.

Here's a short description of the way I apply metafiltering in my project:

Scenario: I want to filter story execution by Meta
Meta:
@context clientCode1
Given ...
When...
Then...

or By using example tables such as:

Scenario: I want to filter story examples execution by Meta
Meta:
@context
Given ...
When...
Then...
Examples:
|clientCode|
|clientCode1|
|clientCode2|

I'm running serenity test execution using serenity-maven-plugin and setting environment variable as follows:
-Dmetafilter="+context clientCode1 +featureA -featureB

In order to be able to keep the existing filtering feature in my repos I had to revert back to serenity-jbehave v 1.6.0

Can you tell if I miss something on if there is a sneaky bug or something ?

**Comment by samuelMangot** [comment]
Hi John, 

Thanks for your quick answer. 
That could be a possibly root cause of the issue...
The jbehave upgrade is the most outstanding recent change as far I see.

**Comment by samuelMangot** [comment]
I can find a issue reported on jbehave side which is pretty close to mine.
So it's definitely not a serenity issue ! 
Thanks again for the hint John!
